/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nemo.nmcnpm.Frame;

import jakarta.persistence.Entity;
import jakarta.persistence.EntityManager;
import java.awt.BorderLayout;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    private EntityManager em;
    private MainPanel mainPanel;

    public MainFrame(EntityManager em) {
        initComponents();
        this.em = em;
        this.mainPanel = new MainPanel(this, em);
//        setContentPane(mainPanel);
        add(mainPanel, BorderLayout.CENTER);
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Module Quản lý nhân viên\n");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(675, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
